### ISSUE TITLE
filewatcher -> chokidar?

### ISSUE THREAD

**Issue by kachkaev** [whitecolor/ts-node-dev#10]
I might be worth considering a shift from `filewatcher` to `chokidar`, which is some sort of an industry standard and thus has smaller chances for failures on various platforms.

* https://www.npmjs.com/package/filewatcher
* https://www.npmjs.com/package/chokidar

**Comment by kachkaev** [comment]
Not that I'm aware of. However, IMO there is a higher chance for them to appear in various edge cases, especially when it comes to running `ts-nod-dev` on different platforms.

I submitted this issue after finding `filewatcher` in `ts-node-dev` dependencies and then trying it in my own project. Because this module did not support recursive watching I needed in my case, I began to search for alternatives, stumbled across `chokidar` and realised how large the difference between the two is.

Feel free to close this issue if you don't see enough benefits that would cover your time costs – as I've said, `ts-node-dev` does work for me. However, if you agree that a dependency with just 26 stars and the last update one ago can bring hidden risks, I'll be happy if you consider switching to `chokidar`!

**Comment by whitecolor** [comment]
> a dependency with just 26 stars 

I believe `filewatcher` module was created specifically for `node-dev` by its author, so it does only what it needs to do, without excessive deps. So always look deeper, than just gh stars. ) 

Ну и как говорят в наших краях: "работает - не трогай" ;)

So I will close the issue for now.
