### ISSUE TITLE
Watch node_modules for changes

### ISSUE THREAD

**Issue by hybridmuse** [whitecolor/ts-node-dev#109]
I want ts-node-dev to watch node_modules/@namespace for changes (those are local symlinked dependencies).
But README says "by default /node_modules/ are ignored".

I tried the following, which is not working:
```
ts-node-dev --watch node_modules/@namespace -- my-script.ts
```
Force watching the whole node_modules folder doesn't seem to work either:
```
ts-node-dev --watch node_modules -- my-script.ts
```
Any help appreciated.

**Comment by headghost** [comment]
My bad, resolved with node-dev' flags (`--no-deps` for own files and linked modules, `--all-deps` for all dependencies.

**Comment by hybridmuse** [comment]
My bad, resolved with node-dev' flags (--no-deps for own files and linked modules, --all-deps for all dependencies.
