### ISSUE TITLE
Source maps don't seem to refresh immediately?

### ISSUE THREAD

**Issue by artemzakharov** [whitecolor/ts-node-dev#11]
First off - mad props for this lib! It's the only means I've come across for implementing proper debugging with TS on the server side, owing to the fact that it's all a single process, which makes it possible to reload files without losing the debugging session. 

I have run into a small problem, though - when I'm debugging my app in VS Code and I set a breakpoint, the breakpoint won't work anymore if the file is reloaded. Hovering over gives this message:

`Unverified breakpoint, Breakpoint ignored because generated code not found (source map problem?).`

If I disable and re-enable the breakpoint, it works again. Any idea what might be going on here? I would understand fully if you this is something out of your control, but I wanted to ask nonetheless to see if I missed something obvious. I recall hearing that the `--nolazy` flag is used to fix this with normal node, so maybe this is related?

This is my debugging launch config:

```
    {
      "type": "node",
      "request": "launch",
      "name": "ts node dev",
      "runtimeExecutable": "ts-node-dev",
      "args": ["--respawn", "--type-check", "src/index.ts"],
      "envFile": "${workspaceFolder}/.env",
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "sourceMaps": true
    }
```

**Comment by whitecolor** [comment]
Hi, I just never work with source maps and not sure how it is working, though I believe something could be done with your issue. I will try to have a look when I have time.

**Comment by artemzakharov** [comment]
@whitecolor Thank you! In the meantime, I've come up with a hilariously hacky solution... have nodemon run a VB script that presses my keybinds for me! For anyone else wanting to do this, here's how it works:

1. Bind disable breakpoints and enable breakpoints to something, Ctrl+F11 and Ctrl+F12 in this example
2. Create `keys.vbs`:
```
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.AppActivate "Visual Studio Code"
WScript.Sleep 100
objShell.SendKeys "^{F11}"
WScript.Sleep 100
objShell.SendKeys "^{F12}"
```
3. Run it as follows:
`nodemon -e ts -x cscript keys.vbs`

Viola, nodemon will now "refresh" your breakpoints on every TS reload.

**Comment by whitecolor** [comment]
> . is there any way to run a custom script after a refresh with ts-node-dev, the same way you can with nodemon?

Well, you may wrap your js/ts stript with custom logic which will be executed on each restart.

**Comment by artemzakharov** [comment]
@whitecolor That's what I get for overthinking things, thanks! I'll post an update to how to do this once I figure it out, for anyone else who runs into this issue.

**Comment by artemzakharov** [comment]
Looks like VS code refreshes breakpoints on its own now, so closing issue.
