### ISSUE TITLE
folders not watching in src

### ISSUE THREAD

**Issue by KyDenZ** [whitecolor/ts-node-dev#111]
Hello,

I just discovered your project that interests me a lot. I currently use nodemon + ts-node to restart my server when I modify a file.
The contents of the files of my server is in the folder src :

src:
- models
- interface
- middlewares

With nodemon my server restarted when I edit a file in any folder. With ts-node-dev the server restarts when I edit a file in the model folder or folder at the root of the server,  but not when I modify a file in interface or middleware.

my script start: 
"start": "ts-node-dev --no-deps src/server.ts"

thanks

**Comment by whitecolor** [comment]
Watches only required files

**Comment by whitecolor** [comment]
but there is also `--watch` option
--watch - Explicitly add files or folders to watch and restart on change (list separated by commas)
