### ISSUE TITLE
--compiler flag is not working

### ISSUE THREAD

**Issue by soanvig** [whitecolor/ts-node-dev#117]
Hello. I try to use `--compiler` option:

```sh
ts-node-dev --compiler ttypescript ./src/index.ts
```

though it has no effect.

Everything works with:

```sh
 ts-node --compiler ttypescript ./src/index.ts
```

I looked into source code, and everything seems to be in place, so I cannot even submit PR.

Any idea, why it may happen? I can create example repository, if that helps

**Comment by Cpecific** [comment]
Issue starts with ts-node@8.6.0. You can revert to ts-node@8.5.4 for now.
And would be better to report this into ts-node issues.

**Comment by Rajeshr34** [comment]
Fixed??

**Comment by soanvig** [comment]
@Cpecific at first glance I thought it's ts-node-dev issue, but today I tried to use that flag in ts-node, and it seemed to fail too.

Thank you for package version info.

Gonna report that in ts-node, after verification.

**Comment by soanvig** [comment]
@Cpecific I have `ts-node@8.5.2` installed:

```
├─ ts-node-dev@1.0.0-pre.44
│  ├─ ts-node@*
├─ ts-node@8.5.2
```

**Comment by soanvig** [comment]
Fixed by adding

```json
"resolutions": {
    "ts-node": "8.5.4"
  }
```

For `yarn` to lock that version even for dependencies. `npm-shrinkwrap` may do a job for you, if you are using npm.

**Comment by IgorSzymanski** [comment]
I might be wrong, but I don't think it's a `ts-node` issue.
I'm using:
```json5
// abstract of package.json
{
	"main": "dist/main.js",
	"scripts": {
		"build": "ttsc",
		"start:dev": "ts-node-dev --compiler ttypescript --respawn --transpileOnly src/main.ts",
		"start": "node dist/main.js"
	},
	"devDependencies": {
		"@zerollup/ts-transform-paths": "1.7.17",
		"ts-node": "8.9.0",
		"ts-node-dev": "1.0.0-pre.44",
		"ttypescript": "1.5.10",
		"typescript": "3.8.3"
	}
}

```

```json5
// tsconfig.json
{
	"compilerOptions": {
		"lib": ["esnext", "es6", "dom"],
		"module": "commonjs",
		"moduleResolution": "node",
		"declaration": false,
		"noImplicitAny": true,
		"removeComments": true,
		"noLib": false,
		"skipLibCheck": true,
		"strictNullChecks": true,
		"allowSyntheticDefaultImports": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"strictFunctionTypes": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"target": "es2018",
		"sourceMap": true,
		"strict": true,
		"allowJs": true,
		"checkJs": false,
		"forceConsistentCasingInFileNames": true,
		"alwaysStrict": true,
		"plugins": [{ "transform": "@zerollup/ts-transform-paths" }],
		"outDir": "./dist",
		"baseUrl": "./src",
		"paths": {
			"~/*": ["*"]
		}
	},
	"include": ["src/**/*"],
	"exclude": ["node_modules", "dist"]
}

```

Running `yarn build && yarn start` works perfectly — output code is transpiled via `ttypescript` with `@zerollup/ts-transform-paths` plugin and all the alias paths are resolved correctly.
Running `yarn start:dev` results in errors like:
```
Error: Cannot find module '~/models'
```

**Comment by whitecolor** [comment]
There is a test shows it works
https://github.com/whitecolor/ts-node-dev/blob/master/test/index.ts#L147

Reopen if actual.

**Comment by hajnalbendeguz** [comment]
If anyone is looking for a solution here is one. I was using ttypescript and @zerollup/ts-transform-paths. For me ttsc worked fine, but not ts-node or tsnd. https://stackoverflow.com/a/51666714/8384179 saved me.

**Comment by whitecolor** [comment]
`--files` option may slow down things when used unconsciously.
