### ISSUE TITLE
Non-function paramtypes rewritten to Object

### ISSUE THREAD

**Issue by draconisNoctis** [whitecolor/ts-node-dev#126]
I'm using a little hacky solution in my NestJS projekt where I overwrite a string-const export with a type.

```
export type Configuration<T extends {} = {}> = T & InferConvict<typeof DEFAULT_SCHEMA>;
export const Configuration = 'CONFIGURATION' as unknown as Type<Configuration>;
```

So I can use this construct to inject a dependency with the proper typing

```
class Example {
    constructor(protected readonly config: Configuration) {}
}
```

This works well in `ts-node`, as with `tsc` and `node` but not with ts-node-dev. The reason is the following generated code:

```
let Example = class Example {
    constructor(config) {
        this.config = config;
    }
}
Example = __decorate([
    __metadata("design:paramtypes", [typeof (_a = typeof configuration_1.Configuration !== "undefined" && configuration_1.Configuration) === "function" ? _a : Object]
]);
```

Is there an option to disable this "feature"?

**Comment by whitecolor** [comment]
Not sure I get. Could you add a reproduce code snippet to test it?

**Comment by whitecolor** [comment]
Will close, reopen if needed.
