### ISSUE TITLE
Problem with using worker_threads

### ISSUE THREAD

**Issue by brunocangs** [whitecolor/ts-node-dev#132]
I'm trying to write a code that uses worker_threads for some background processes, and I'm having the following issue:

> Running the code with `ts-node` works but with `ts-node-dev` doesn't.

The code I used for testing is the following:
index.ts
```typescript
import { TSWorker } from './ts-worker';

const worker = new TSWorker("./test.ts");
worker.on("message", console.log);
worker.on("exit", code =>
  console.log(`Worker with ID ${worker.threadId} exited with code ${code}`)
);
```
test.ts
```typescript
import { parentPort } from 'worker_threads';
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
let arr: any[] = [];
const SIZE = 1000000;
(async function() {
  while (arr.length !== SIZE * 10) {
    await sleep(1000);
    arr = arr.concat(
      Array.from({ length: SIZE }, () => ({
        a: Math.random(),
        b: Math.random(),
        c: Math.random(),
        d: Math.random()
      }))
    );
    parentPort && parentPort.postMessage(arr.length);
  }
  return 2;
})().then(console.log);
```

ts-worker.js
```javascript
const path = require("path");
const {
  workerData,
  isMainThread,
  Worker,
  parentPort
} = require("worker_threads");

class TSWorker extends Worker {
  constructor(path, opt = { workerData: {} }) {
    return new Worker(__filename, {
      ...opt,
      workerData: {
        path,
        ...opt.workerData
      }
    });
  }
}
if (isMainThread) {
  module.exports = { TSWorker };
} else {
  try {
    require("ts-node").register({
      project: path.resolve(__dirname, "tsconfig.json")
    });
    require(path.resolve(__dirname, workerData.path));
  } catch (e) {
    console.error(e);
    parentPort.postMessage(e);
  }
}
```

The application's output when running it on `ts-node` is 
![image](https://user-images.githubusercontent.com/30100875/76652370-371cbb00-6545-11ea-9c27-2873c89c95bd.png)

and when running with `ts-node-dev`
![image](https://user-images.githubusercontent.com/30100875/76652392-469c0400-6545-11ea-9b37-44a7b2d7ef06.png)

Thanks

**Comment by munkhorgil** [comment]
@brunocangs I have the same problem with nodejs v12.16.3, It works fine in node v10. Did you find any solution?

**Comment by eugene1g** [comment]
The part that's causing troubles is https://github.com/whitecolor/ts-node-dev/blob/24813393769d23da9e585c157b3375f594ecba5e/lib/child-require-hook.js#L37-L40

Specifically, `process.send` is an IPC method and it's `undefined` inside a worker (See https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback). One quick hack is to comment-out that code, and then `ts-node-dev` plays nice with workers for me. I'm unsure if it breaks anything else, or if there is an easy permanent solution.

**Comment by whitecolor** [comment]
I will add a check if `process.send` exists.

**Comment by denkomanceski** [comment]
Also, commenting out the code as @eugene1g mentioned works. Just remember that if you call `ts-node-dev` from command line, it is using the globally installed module, so changing in the project's node_modules wont do anything. Calling `ts-node-dev` from package.json scripts is using the local node_modules folder

**Comment by whitecolor** [comment]
denkomanceski check if the latest publish works for you.
