### ISSUE TITLE
--watch doesn't accept pattern?

### ISSUE THREAD

**Issue by woss** [whitecolor/ts-node-dev#140]
i'm trying to run the script like this 

` "start": "tsnd --respawn  --watch ./src/**/*.ts ./src/index.ts",` 

and the function in index never tuns, but this 

` "start": "tsnd --respawn  --watch ./src ./src/index.ts",` 

does work.  What if i have other files and i would like to watch only `ts` files

**Comment by whitecolor** [comment]
now it should with `chokidar`
