### ISSUE TITLE
Document the `rs` flag and disable it by default

### ISSUE THREAD

**Issue by Etheryte** [whitecolor/ts-node-dev#147]
Currently, the setup script [automatically hijacks the user's terminal](https://www.karltarvas.com/2020/05/31/ts-node-dev-binds-to-stdin-via-readline-by-default.html) without this being documented anywhere.  

See the source [here](https://github.com/whitecolor/ts-node-dev/blob/c0df64c43455d2f8ef144eb9defcd05b6fc52486/lib/index.js#L59):

```ts

// Read for "rs" from command line  
if (opts.rs !== false) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
  })
  rl.on('line', ...);
}
```

This is both undocumented and **not** what a pick and place `node-dev` replacement should do by default.  

This straight up breaks any program that wants to read from the stdin themselves.  

**The proposed solution:**  

 - This behavior should be **opt-in**, not op-out. That is, `rs` should be `false` by default
 - The flag should be documented similar to other options.

**Current workaroud:**

Specify `--rs false` in your `package.json`:

```json
{
  "scripts": {
    "serve": "ts-node-dev --respawn --rs false index.ts"
  }
}
```

**Comment by whitecolor** [comment]
Disabled.
