### ISSUE TITLE
Infinite 'uncaughtException' loop

### ISSUE THREAD

**Issue by aikoven** [whitecolor/ts-node-dev#15]
Sometimes when my app crashes, it gets into an infinite loop of uncaught exceptions.

Stack trace:

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:613:16)
    at Object.exports.send (/opt/app/node_modules/ts-node-dev/lib/ipc.js:14:23)
    at process.<anonymous> (/opt/app/node_modules/ts-node-dev/lib/wrap.js:45:7)
    at process.emit (events.js:187:15)
    at process.emit (/opt/app/node_modules/source-map-support/source-map-support.js:454:21)
    at process._fatalException (internal/bootstrap/node.js:435:27)
```

**Comment by aikoven** [comment]
Also, a comment near `uncaughtException` says that the handler is there to log the stack to `stderr`. Can I somehow omit this? My app already logs uncaught exceptions, so I get the stack printed twice.

**Comment by whitecolor** [comment]
> Sometimes when my app crashes, it gets into an infinite loop of uncaught exceptions.

Not sure I understand what is an infinite loop of uncaught exceptions.

> Also, a comment near uncaughtException says that the handler is there to log the stack to stderr.

You want to omit the output or `uncaughtException` handling by `ts-node-dev`?

**Comment by aikoven** [comment]
There's an `uncaughtException` handler in `wrap.js`:

```js
process.on('uncaughtException', function (err) {
  console.error(err.stack || err);
  // If there's a custom uncaughtException handler expect it to terminate
  // the process.
  var hasCustomHandler = process.listeners('uncaughtException').length > 1;
  ipc.send({
    error: err.name || 'Error',
    message: err.message,
    willTerminate: hasCustomHandler
  });
});
```

The `ipc.send` call under some circumstances throws an exception with stack trace I've posted above. Which in turn triggers the same `uncaughtException` handler.

> You want to omit the `uncaughtException` error stack output or its actual handling by ts-node-dev?

The output.

**Comment by whitecolor** [comment]
Ok, I get it, this happens because exception by `ipc.send` producessed asynchronisly. We can handle it.

> The output.

So I believe we can omit the output if `hasCustomHandler `.

**Comment by whitecolor** [comment]
Check the latest version, should be fixed I believe.

**Comment by aikoven** [comment]
Wow, thanks for a fast resolution! 

It seems to have fixed the problem I had. Thanks!

**Comment by capaj** [comment]
yeah it seems fixed here as well. Also with ` "ts-node-dev": "^1.0.0-pre.24",` my app took like 6 seconds to restart, now it's almost instant. Thank you so much @whitecolor !

**Comment by whitecolor** [comment]
@capaj is it pre.24? Check the latest version works for you please because pre.24 had this issue #17

**Comment by iAnomaly** [comment]
@whitecolor This bug regressed for me starting with pre.24 onwards and even in latest: pre.44. Working great (not reproducible) in pre.23.

**Comment by evantahler** [comment]
I'm having the same experience as @iAnomaly.  The 🐛 is back! 

In my case, the behavior can be triggered in an application that handles it's own shutdown behavior via `process.on("SIGTERM", async () => {`. It doesn't have to be a "crash" per-se...

**Comment by omerxx** [comment]
@whitecolor Got this too after updating some libs. Any chance this is fixed?
Is the project maintained / has alternatives?

Thanks!

**Comment by elgambet** [comment]
Im having this problem. 

In my case using **process.stdin.on("keypress")** generates the error if removed, the loop does not happens.
