### ISSUE TITLE
`ts-node-dev --compiler ttypescript` fails to load .ts transformers

### ISSUE THREAD

**Issue by jakzo** [whitecolor/ts-node-dev#150]
Running `ts-node-dev --compiler ttypescript` fails to load transformers which are `.ts` files.

I've narrowed down the issue to the way ts-node-dev handles compilation in the main process. I'm opening a PR with an explanation of the fix.

**Comment by whitecolor** [comment]
@jakzo 

didn't work with TS transformers but added the tests:
https://github.com/whitecolor/ts-node-dev/blob/master/test/index.ts#L162

If the issue still relevant, could you elaborate on it?

**Comment by whitecolor** [comment]
Reopen if actual.
