### ISSUE TITLE
Unexpected end of JSON input while parsing near '...ersion":"1.4.0","depe'

### ISSUE THREAD

**Issue by Rajuchoudhary** [whitecolor/ts-node-dev#152]
when I run this command:

**npm i ts-node-dev --save-dev**

it gives me this error:

**npm ERR! Unexpected end of JSON input while parsing near '...ersion":"1.4.0","depe'**

**Comment by whitecolor** [comment]
Probably something wrong with your package.json, not ts-node-dev

**Comment by Rajuchoudhary** [comment]
I used the same cmd with yarn and it worked but with npm it gave me this
error. And in the console it was saying to report a problem.
