### ISSUE TITLE
Compilation errors are reported but code stops executing

### ISSUE THREAD

**Issue by DarkLite1** [whitecolor/ts-node-dev#153]
First of all, thank you for this wonderful piece of software. It's really great not having to use `nodemon` or `tsc-watch` anymore and to work with compiled `.js` files.. I really think and hope that TypeScript will be the future.

Now on to the issue. When working with `ts-node-dev` I encountered the same issues as [#609](https://github.com/TypeStrong/ts-node/issues/609). Errors are correctly reported in the console when adding the `--type-check` [flag](https://github.com/whitecolor/ts-node-dev/issues/119) but when an error is encountered the code stops executing which is a bit annoying.:

```js
// errors reported, script stopped
"dev": "ts-node-dev --type-check --respawn src/index.ts",
```
I've tried the suggestion of adding the [flag](https://github.com/TypeStrong/ts-node/issues/609) `--log-error` but then no errors are reported in the console but the script does continue:

```js
// no errors reported, script continues
"dev": "ts-node-dev --type-check --log-error. --respawn src/index.ts",
"dev": "ts-node-dev --type-check --transpile-only --respawn src/index.ts",
```

Ideally I would like `ts-node-dev` to report all TS errors in the console but don't stop the execution of the code on compilation errors. Would something like this be possible?

Versions:
```js
"ts-node": "^8.10.2",
"ts-node-dev": "^1.0.0-pre.44",
"typescript": "^3.9.5"
```

Thank you for looking into this.

**Comment by whitecolor** [comment]
> the code stops executing which is a bit annoying

It should stop and wait for the error to be fixed. No?

**Comment by DarkLite1** [comment]
Ideally I would like `ts-node-dev` to report all TS errors in the console but don't stop the execution of the code on compilation errors. The code could still contain valid javascript code that woud work flawless. So no, it should not stop on errors, only report the errors to the console..

**Comment by whitecolor** [comment]
I think it is a bit strange approach, if you don't want to TS errors affect the runtime execution just use `--transpile-only`. All the errors are still usually highlighted in the editor, so you can see them anyway, I don't see a reason to add them to the terminal output considering they not really affect the flow.

**Comment by DarkLite1** [comment]
True, that is a workaround. But then you can only see the errors in vs code. So you need to open every file to see the red lines. It would be nice to have an option to see the errors in the console but keep the program running. Maybe add another flag?

`ts-node-dev --stopExecutionOnTSerror`
`ts-node-dev --showErrorsInConsole`

With flags like this the user is free to select the behavior the wants.

**Comment by whitecolor** [comment]
Well first of all `ts-node-dev` (the same `ts-node`) is code executing tool, typechecking is optional if you want it to affect execution flow. To do what you ask would require to perform two types of compilation (in case of type error), which is not impossible, but seems redundant.

If you consider **Type Errors to be important** I would really recommend using typecheking and fix issues as you encounter them, stopping execution of code with errors only helps. Otherwise, if type errors are not important (if you prefer speed, and see typechecking as helping tool while development) just only use transpilation and make full type checking later on the relevant steps (like test, build, etc). It seems to me that what you are trying to achieve is a bit incorrect in terms of dev process logic to combine thigs that are better separate, this is my opinion on the issue.

**Comment by DarkLite1** [comment]
Thank you for your feedback. Although I don't completely agree I do appreciate your point of view. 

I'm new to development with TS and I'm trying to find a way of coding that works for me. To do this it seems to be nice to just be able to run `npm run dev` have it execute `ts-node-dev` and show compilation errors in the console so I can go fix them but still execute the program when possible. This will allow only one console to be visible with all the TS errors there are and not having to hunt down the IDE for red squiggle lines.

Thank you for reconsidering.

**Comment by whitecolor** [comment]
I just see this as a kind of a mess when you will see the errors in the console but execution continues. Ok, maybe reconsider later, if there will be more inquiries.

**Comment by DarkLite1** [comment]
Thank you Alex, appreciate it. With the extra flags you can just tell users to use them as they desire. That way that can have what they want. You the functionality already in the code, it's just not modular enough to be used with a flag. 

Anyhow, here's me hoping for some thumbs up on this request :)

**Comment by whitecolor** [comment]
@DarkLite1 
`--log-error` actually should work as expected, I never used this `ts-node` option before. Here is the test for this https://github.com/whitecolor/ts-node-dev/blob/master/test/index.ts#L95

**Comment by DarkLite1** [comment]
@whitecolor this does indeed fix my problem. Thank you for looking into this. Using that option now. Closing this one :)
