### ISSUE TITLE
Version 1.0.0-pre.48 crashes with Heap Out of Memory error

### ISSUE THREAD

**Issue by n8sabes** [whitecolor/ts-node-dev#160]
When a .ts file has errors, after a ~minute idling waiting for updates, the process crashes with the following error:

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

This does not seem to occur in pre.47.

**Comment by whitecolor** [comment]
Oh, will fix that.

**Comment by whitecolor** [comment]
Should be fixed.

**Comment by n8sabes** [comment]
**That did it -- FIXED! Thank you!**

@whitecolor BTW, a naivety question: I see the 1.0.0-pre.XX releases on NPM, but not under the Releases tab, nor see the code fix commit under any branch/tags. Are these fixes from another GitHub fork, a private repo, or....?? Just trying to learn something new.

Thanks again for `ts-node-dev`, and for the fix!!

**Comment by n8sabes** [comment]
@whitecolor I thought it was fixed, but still getting the crash when left in a non-compiling state.

```
<--- Last few GCs --->

[8423:0x1045ed000]  2359656 ms: Mark-sweep 2042.9 (2052.6) -> 2042.5 (2052.4) MB, 1237.3 / 0.0 ms  (average mu = 0.078, current mu = 0.002) allocation failure scavenge might not succeed
[8423:0x1045ed000]  2360714 ms: Mark-sweep 2043.1 (2052.4) -> 2042.7 (2052.6) MB, 1055.9 / 0.0 ms  (average mu = 0.044, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10123d2a5 node::Abort() (.cold.1) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 2: 0x10009dd29 node::Abort() [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 3: 0x10009de8f node::OnFatalError(char const*, char const*) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 4: 0x1001d9db7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 5: 0x1001d9d57 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 6: 0x10036c885 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 7: 0x10036e11a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 8: 0x10036a075 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
 9: 0x100367afe v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
10: 0x100374e3a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
11: 0x100374ec1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
12: 0x1003412a7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
13: 0x1006a7be8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
14: 0x1009f3899 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/n8/.nvm/versions/node/v14.4.0/bin/node]
15: 0x1d5b3c174d5
16: 0x1d5b3be187b
17: 0x1d5b3c1a545
/bin/sh: line 1:  8423 Abort trap: 6           ts-node-dev --inspect --clear ./src/index.ts
```

**Comment by whitecolor** [comment]
@n8sabes is it `pre.49`?

**Comment by n8sabes** [comment]
@whitecolor, yes 1.0.0-pre.49.

**Comment by whitecolor** [comment]
@n8sabes is it happening for a certain project/code? Or for any?

**Comment by n8sabes** [comment]
@whitecolor It's happening in a medium size project. I have not built a new clean test project to test against, but can do that. I can also roll back to 1.0.0-pre-4x to see if it was occurring in the prior releases.

**Comment by whitecolor** [comment]
Ok try to run your crashing probject also without `--inspect` flag.

**Comment by n8sabes** [comment]
**TEST 1:** I have run a test based on a random clean starter [typescript-express-starter](https://github.com/ljlm0402/typescript-express-starter) and let it sit in an error state for 6 hours. No crash has resulted so far. Obviously there are differences, such as being much smaller, and no active development recompiles are happening that do with my primary project.

**TEST 2:** Yes, I will test my mid-size project without the --inspect flag and report back.

@whitecolor Do you have any recommendations on how to track the origin of this crash? The crash's console isn't meaningful (to me), so I'm not sure where to look or how to help diagnose it. My project is large and complex enough that division/pruning or migrating code to a clean baseline would be a lengthy effort.

**Comment by whitecolor** [comment]
Well, there is some memory leak, I'm not sure if a leak in you app may cause this, you may also try running with `--debug` flag to get more details on ts-node-dev process.

**Comment by n8sabes** [comment]
I'll run with `--debug` and no `--inspect` and let your know what happens.

_Since the app is not running in the failed compile state, not sure a memory leak from the app is the catalyst, but I could be wrong. I have been scratching my head what in the project may have changed (from the code, scripts / config, to toolchain). I upgraded packages today, so unfortunately injected another element of change._

Thank you.
