### ISSUE TITLE
Feature request: remove node-notifier dependency

### ISSUE THREAD

**Issue by MarcusCemes** [whitecolor/ts-node-dev#161]
## Feature Request

Remove the node-notifier dependency, and fallback to showing a message in the terminal, or nothing at all.

## Motivation

https://github.com/mikaelbr/node-notifier/issues/314
This has been open for a while now, it doesn't look like it will get any attention. `node-notifier` will modify a user's start menu (on Windows and on macOS it seems) to point a shortcut to the vendor directory in `node_modules`. It's unnecessary.

Also, I find the _constant_ bell sound whenever I make the slightest change to a file _very annoying_.  I don't need to receive a notification to know that I've changed a file, I already knew that, and it fills up the notification list.

`ts-node-dev` is a fantastic idea, but I won't be using it more without some of these issues being resolved.

**Comment by merceyz** [comment]
Just as a note: You can disable the notifications using `ts-node-dev --no-notify ./index.ts`
