### ISSUE TITLE
Error in installation of 1.0.0-pre.51 version

### ISSUE THREAD

**Issue by BrunoSilveiraDev** [whitecolor/ts-node-dev#168]
I tried to install the ts-node-dev in 1.0.0.-pre.51 version with yarn **``yarn add ts-node-dev``** and I got this error:

```bash
$ ts-node-dev --transpileOnly --ignore-watch node_modules src/server.ts
Using ts-node version 8.10.2, typescript version 3.8.3
/usr/local/bin/node: bad option: --transpileOnly
error Command failed with exit code 9.
```
and in the installation, using the command **``yarn add ts-node-dev``**, I had realized that uncommon part:

```bash
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
```

Have someone an idea about it ?
Could this have been the version update?

**Comment by BrunoSilveiraDev** [comment]
The argument of ts-node-dev **``--transpileOnly``** has changed to **``--transpile-only``**.

**Comment by whitecolor** [comment]
Yes flags correspond to current version of `ts-node`.
