### ISSUE TITLE
1.0.0-pre.50 -> 1.0.0-pre.51 d.ts file are ignored

### ISSUE THREAD

**Issue by n1ru4l** [whitecolor/ts-node-dev#169]
**tsconfig**:
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "./../server-build"
  },
  "include": ["./"]
}
```

**global.d.ts**
```tsx
declare module NodeJS {
  interface Process {
    pkg: undefined | boolean;
  }
}
```

Error after upgrading to `ts-node-dev@1.0.0.0-pre.51`:

```
[ERROR] 12:38:30 ⨯ Unable to compile TypeScript:
server/util.ts:14:15 - error TS2339: Property 'pkg' does not exist on type 'Process'.

14   if (process.pkg) {
                 ~~~
```

When installing the previous version everything works as expected (`npm install -D -E ts-node-dev@1.0.0.0-pre.50`)

**Comment by whitecolor** [comment]
There actually was a `bug` in ts-node-dev whih made it work slower

Read the docs of `ts-node.`
https://github.com/TypeStrong/ts-node#help-my-types-are-missing

**Comment by n1ru4l** [comment]
@whitecolor Thanks for the information!

I solved it the following way: https://github.com/dungeon-revealer/dungeon-revealer/pull/577

More context can be found here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

> A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.

**Comment by marcoreni** [comment]
This broke our build as well. In our case, since we had a module definition, we had to use 
```js
"compilerOptions": {
  "baseUrl": ".",
  "paths": {
    "{module-name}": [
      "src/types/{filename}.d.ts"
    ]
  }
}
``` 

Maybe it can be pointed out somewhere in the readme? I'd say it belongs to release notes but I cannot find any...
