### ISSUE TITLE
pre.24 is really slow and sometimes doesn't trigger restart

### ISSUE THREAD

**Issue by ErikMartensson** [whitecolor/ts-node-dev#17]
After updating to pre.24 I've noticed that my process doesn't restart correctly. Sometimes it just hangs forever and sometimes it will restart, but it will take at least 20 seconds. 

When using pre.23 it always restarts and it takes 2-5 seconds max.

For pre.24 it seems to recognize file changes because I see this output:
```
[INFO] 07:57:47 Restarting: /code/src/controllers/misc.ts has been modified
```
But then it goes quiet until I restart my Docker container.

Running Windows 10 host with Docker containers on image `node:8.11.1`. Everything related to node.js is running within the container.

**Comment by whitecolor** [comment]
That's intresting. Do you have a big project? Changes were made due to #6. Probably will have to rollback.

**Comment by ErikMartensson** [comment]
This project is around 400 TypeScript files.

**Comment by whitecolor** [comment]
>Sometimes it just hangs forever and sometimes it will restart, but it will take at least 20 seconds.

Does first start up time differs in 23 vs 24? Or the problem only with restarts?

**Comment by ErikMartensson** [comment]
Both of them differs. pre.23 is way faster in both scenarios.

**Comment by ORbannes** [comment]
Same problem here

**Comment by whitecolor** [comment]
Ok, i've published pre.26 with rolled back compilation, so check it.

**Comment by ErikMartensson** [comment]
pre.26 seems to work great for me, even a bit faster than pre.23.
Thanks for improving my workflow!

**Comment by ORBak** [comment]
It's effective, working quickly 

Thank you
