### ISSUE TITLE
Question: Can the spawned process request a restart?

### ISSUE THREAD

**Issue by loreanvictor** [whitecolor/ts-node-dev#176]
So I have this process, who also watches for changes in some other files and reacts to these changes, but those files aren't watched by ts-node-dev as changes in them shouldn't cause a restart of the process. sometimes though, I'd love to restart the process in response to changes in those files. right now the only way I have is to save part of the code itself (i.e. `__filename`) so that ts-node-dev restarts the process. is there a cleaner way, something like `process.send('ts-node-dev please restart although no files changed?')`

**Comment by whitecolor** [comment]
Your script can touch yourself and it will cause the restart.

**Comment by loreanvictor** [comment]
thats what it is doing right now. I was wondering if there was a neater way.

**Comment by whitecolor** [comment]
I think it is quite neat) Not sure if there is really need in special method to ask for reload from child.

**Comment by loreanvictor** [comment]
cool, thanks for the answer anyways.
