### ISSUE TITLE
Support for jsx files

### ISSUE THREAD

**Issue by noveyak** [whitecolor/ts-node-dev#178]
Although a bit odd, I currently have some source files which end in .jsx. Normally tsc supports these  as long as allowJs is set to true and I verified that ts-node supports this out of the box. When I use ts-node-dev I get an error saying ` Error: Cannot find module './b'` (if b is a jsx file). This seems to be because ts-node-dev does not register the jsx extension.

I did a pretty simple workaround in `child-require-hook` by just adding `require.extensions['.jsx'] = require.extensions['.js']` and changing the code to also look for a .jsx ext and it seems to work ok for me at first glance. Could we look at possibly adding support for the jsx file extension in ts-node-dev?

**Comment by whitecolor** [comment]
Should work now.
