### ISSUE TITLE
Spaces in project path will break ts-node-dev

### ISSUE THREAD

**Issue by BrunoScheufler** [whitecolor/ts-node-dev#18]
When running ts-node-dev in a project which contains spaces in its directory path, it will simply crash. The error message is along the lines of `Error: Cannot find module 'C:\Users\USER\All'` where the path should b e `C:\Users\USER\All Projects\...`. Maybe this is just Windows-related.

**Comment by whitecolor** [comment]
You mean cwd location dir? Or script path with spaces? if so try to use quotes.

**Comment by BrunoScheufler** [comment]
it's the cwd location dir I guess

**Comment by BrunoScheufler** [comment]
My command in that case is `ts-node-dev [some arguments] src/index.ts where my cwd path contains a space

**Comment by whitecolor** [comment]
It seems to work for me:
![image](https://user-images.githubusercontent.com/736697/40981124-a0707b96-68f3-11e8-8dba-6b9ebb484935.png)

Not sure how to reproduce it.

**Comment by BrunoScheufler** [comment]
@whitecolor that's indeed strange. Maybe it's related to my laptop, because on my desktop machine it seems to work now. I'll close this as resolved, thanks for the help nonetheless!
