### ISSUE TITLE
Not reloading on file change

### ISSUE THREAD

**Issue by rafacortese** [whitecolor/ts-node-dev#180]
ts-node-dev not reloading when I change anything and save it.
ver: 1.0.0-pre.52
OS: Windows 10 with WSL2 (ubuntu)

> {
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "tsc",
    "dev:server": "ts-node-dev --respawn --transpile-only --clear src/server.ts"
  },
  "dependencies": {
    "express": "^4.17.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.7",
    "ts-node-dev": "^1.0.0-pre.52",
    "typescript": "^3.9.7"
  }
}

**Comment by rafacortese** [comment]
Oh god, just realized that I need to add the flag --pool. Forget about that, sorry

**Comment by whitecolor** [comment]
`--poll` ;)
