### ISSUE TITLE
bad option: --transpileOnly

### ISSUE THREAD

**Issue by rogeraraujo90** [whitecolor/ts-node-dev#186]
Hello,

I recently ran a `yarn upgrade` to bump my dependencies and the `ts-node-dev` was updated from `1.0.0-pre.50` to `1.0.0-pre.54`. After that I can't use --transpileOnly option:

<img width="890" alt="Screen Shot 2020-07-24 at 20 24 33" src="https://user-images.githubusercontent.com/6045678/88442655-b7083b00-cdeb-11ea-8533-e140555d7a9a.png">

I tried use the latest version but the error still happens. So I backed to version `1.0.0-pre.50` for while.

**Comment by whitecolor** [comment]
`--transpile-only`
