### ISSUE TITLE
Error TS2339: Property 'userId' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs>'?

### ISSUE THREAD

**Issue by gleysonabreu** [whitecolor/ts-node-dev#187]
I'm trying to override an Express Request type. It seems everything is going well until you start the server that gives the error: Error TS2339: Property 'userId' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs>'. I don't know why this is happening. I'm using the lastest version of ts-node-devm.

![IMG_20200724_202933_622](https://user-images.githubusercontent.com/27729455/88443021-0ef37180-cded-11ea-9d92-bcd0e9b46166.jpg)
Help me?? Thanks.

**Comment by whitecolor** [comment]
Try to see this #169

**Comment by gleysonabreu** [comment]
I wore _@types/express.d.ts_ before, but now it's working with _@types/express/index.d.ts_ so works fine now.
