### ISSUE TITLE
on-change/on-failure hooks

### ISSUE THREAD

**Issue by jasonkuhrt** [whitecolor/ts-node-dev#19]
It might be nice to have hooks that run upon every recompile. `tsc-watch` has this feature.

**Comment by whitecolor** [comment]
You mean https://github.com/gilamran/tsc-watch ? How is it comparing to `ts-node-dev`?

**Comment by jasonkuhrt** [comment]
Yes that `tsc-watch`. I prefer ts-node-dev because it shows me console output etc. while tsc-watch is strictly about compiling the codebase. So really, each do different things. Maybe a use-case for the hook is running an npm script after boot like [generating typescript schema types from graphql endpoint](https://github.com/jasonkuhrt/fooql/blob/master/package.json#L26).

Might not be a great use-case.

**Comment by whitecolor** [comment]
Well, you can use for example `-r ./youscript` param (which is a standard node's), it will require this file on each re-run.

**Comment by jasonkuhrt** [comment]
Found a [better solution for my needs actually](https://medium.com/netscape/nodemon-events-run-tasks-at-server-start-restart-crash-exit-93a34c54dfd8). Probably not a good feature request here.

**Comment by whitecolor** [comment]
Well I'll still think about it. Thanks for suggestion.

**Comment by frandiox** [comment]
@whitecolor Did you consider it at the end? It would be nice for doing some codegen:

```js
async onFileChange(filename, ...) {
  if (filename === 'xxx') {
	await generateSomeOtherFile()
  }
}
```
