### ISSUE TITLE
Versions after 1.0.0-pre.50 don't print stack traces for errors

### ISSUE THREAD

**Issue by mogzol** [whitecolor/ts-node-dev#192]
In version 1.0.0-pre.50 and before, if the code threw an error, then a stack trace would be printed along with the regular error line. In all versions since then, only the error message is printed, without the stack trace.

Is there any way to get the stack trace back?

**Comment by whitecolor** [comment]
Will look into it.

**Comment by karimb1** [comment]
I confirm this issue persists in the latest release.

**Comment by whitecolor** [comment]
In `pre.60`?

It should print the error I think. Do you have simple repro example?

**Comment by karimb1** [comment]
Hi @whitecolor, thanks for responding, I originally tested pre.59, but I just updated right now to pre.60 and the stack traces are back.

@mogzol Check with pre.60

Thanks you very much.

**Comment by mogzol** [comment]
Yup, looks like it's fixed in pre.60, thanks!
