### ISSUE TITLE
Is there an option to hide version messages whenever there is a change?

### ISSUE THREAD

**Issue by lamualfa** [whitecolor/ts-node-dev#195]
Every time there is a change, a version message is always displayed. is there a way to hide it?

### Message to hide
`Using ts-node version 8.10.2, typescript version 3.9.7`

### Screenshot
![image](https://user-images.githubusercontent.com/39755201/90478542-759f4d00-e157-11ea-9059-b60e3896fdf3.png)

**Comment by whitecolor** [comment]
Right, made shown only on the first start.

**Comment by lamualfa** [comment]
> Right, made shown only on the first start.

Sorry, but why does this message appear every time a file is changed? (I use `--respawn` option)

**Comment by whitecolor** [comment]
Did you updated to the latest?

**Comment by lamualfa** [comment]
> Did you updated to the latest?

Oh the problem is fixed in `1.0.0-pre.58` version. Thank you very much.
