### ISSUE TITLE
1.0.0-pre.60 not properly clearing terminal

### ISSUE THREAD

**Issue by potb** [whitecolor/ts-node-dev#199]
After updating from 1.0.0-pre.59, I noticed that using the --clear flag won't properly clear my terminal.

Instead, it prints those characters `\033[2J\033[H`.

I tried on VSCode's integrated terminal and the Kitty terminal.

Command ran : `tsnd --respawn --no-notify --clear`

VSCode version : 1.48.0
Kitty version : 0.18.3

**Comment by whitecolor** [comment]
Should be fixed in pre.61.

**Comment by potb** [comment]
Indeed, thanks !
