### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by jumpt57** [whitecolor/ts-node-dev#2]
Hi first time using your module.

I'm using : 
ts-node-dev: 1.0.0-pre.7
npm: 5.6.0
node: 8.9.4
on windows 10

When trying to use it with : 

> ts-node-dev

 or 

> ts-node-dev  --respawn *.ts

through the command line i'm runnning into this error : 

> Error: Cannot find module 'mkdirp'

Can you help me ? Thanks.

**Comment by whitecolor** [comment]
Oh sorry `mkdirp` not in deps, published pre.8, try it.

**Comment by whitecolor** [comment]
you should add ts-node as dependency. I removed it to allow different versions of ts-node to be used.
