### ISSUE TITLE
Invalid "main" entry

### ISSUE THREAD

**Issue by RaFaTEOLI** [whitecolor/ts-node-dev#200]
Hello, I've encountered this error and I can't seem to get rid of it.
![image](https://user-images.githubusercontent.com/40833512/91307828-d694d980-e784-11ea-880e-642d09a9cd25.png)

Here what my package.json looks like:

`{
  "name": "",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev:server": "tsnd --respawn --transpileOnly src/index.ts"
  },
  "devDependencies": {
    "@types/express": "^4.17.7",
    "ts-node-dev": "^1.0.0-pre.61",
    "typescript": "^4.0.2"
  },
  "dependencies": {
    "@types/node": "^14.6.0",
    "express": "^4.17.1"
  }
}
`

Is there anything missing?

**Comment by whitecolor** [comment]
Happens in any project that uses ts-node-dev?

**Comment by RaFaTEOLI** [comment]
Yes, every project i create from now on it throws me that error, i feel like i'm doing something wrong, but i'm following typescript documentation...

Would you advice me a way to debug this error?

I go into the node_modules folder and there's not an index.js file as it said in the error, but since it's a typescript module there's no need right? I might sound like a complete nood haha, but i'm getting into typescript now so...

**Comment by RaFaTEOLI** [comment]
Funny i've tried on a differente machine and it works perfectly fine, i'm trying to figure out why and i'll post the solution here if anyone else encounters this error.

**Comment by whitecolor** [comment]
Maybe `ts-node` package is installed globally on the machine?

**Comment by RaFaTEOLI** [comment]
![image](https://user-images.githubusercontent.com/40833512/91339023-4074a980-e7ac-11ea-8dc2-7f2f1526f7b4.png)
well there's that

**Comment by RaFaTEOLI** [comment]
Here's what I did to fix (don't ask me why)
I ran with npm instead of yarn:

`npm install -D typescript
npm install -D ts-node
npm fun`

![image](https://user-images.githubusercontent.com/40833512/91340915-21c3e200-e7af-11ea-8505-d0d60f1c45d4.png)
![image](https://user-images.githubusercontent.com/40833512/91340963-356f4880-e7af-11ea-9427-fec6bee2e627.png)

**Comment by RaFaTEOLI** [comment]
**UPDATE**

I guess there really was something wrong with my yarn, so I ran `yarn clean cache` and created a new project and now it works perfectly.
