### ISSUE TITLE
Broken with NextJS Custom Server

### ISSUE THREAD

**Issue by rjerue** [whitecolor/ts-node-dev#202]
Hello,

I'm trying to run this with a basic [nextjs custom server](https://nextjs.org/docs/advanced-features/custom-server). Above version 59, I am running into a call stack exceeding

![image](https://user-images.githubusercontent.com/4666313/91910153-55958080-ec63-11ea-8853-9be34cb69929.png)

A minimum example is in the following https://github.com/rjerue/broken-next-server-ts-dev/tree/a3ef3580b5890c8be9441877377707f67cb3109f

A working example, with the previous version, is here: https://github.com/rjerue/broken-next-server-ts-dev/tree/97486b9e23994b0e2061322822688639355d105c

Is there a flag or something I can put in here to prevent this problem?

**Comment by whitecolor** [comment]
Should be fixed in the latest.

**Comment by rjerue** [comment]
Indeed working today. I had also tried the latest. Perhaps it was an issue with some package's semantic versioning having something broken out there. Anyways, thanks for the time.

**Comment by whitecolor** [comment]
> Indeed working today. I had also tried the latest.

I just had fixed it today)

**Comment by rjerue** [comment]
Ahh I see, the changes are published to npm and not git yet. Thank you so much!
