### ISSUE TITLE
ts-node version is fixed

### ISSUE THREAD

**Issue by bwgjoseph** [whitecolor/ts-node-dev#203]
Hi,

since this commit - 06b9759c82311fb3390c9914fb6912a8089f9e84 - `ts-node` version is now fixed rather than what was mentioned in the `README` 

> ts-node dependency version is not fixed, so it will install the latest version by default.

Hence, it doesn't follow the version of local `ts-node` version that I installed with

Is this intended? If so, then maybe the `README` has got to be updated?

Thanks

**Comment by whitecolor** [comment]
Yes it is intended, thanks.

**Comment by falkenhawk** [comment]
@whitecolor are they blockers in compatibility which would prevent upgrading the ts-node dependency to v9.0.0?

**Comment by whitecolor** [comment]
No, I believe , need to test it.

**Comment by daveisfera** [comment]
Would love for `ts-node` to be upgraded to 9.0 for [this fix](https://github.com/TypeStrong/ts-node/issues/1072)
