### ISSUE TITLE
1.0.0-pre.51 causes 'Could not find a declaration file for module'

### ISSUE THREAD

**Issue by plaa** [whitecolor/ts-node-dev#208]
When I upgrade 1.0.0-pre.50 --> 1.0.0-pre.51 (or any later version) I get the following error on startup:

```
Using ts-node version 8.10.2, typescript version 3.8.3
Compilation error in /..../src/config/logger.ts
[ERROR] 14:11:25 ⨯ Unable to compile TypeScript:
src/config/logger.ts:2:48 - error TS7016: Could not find a declaration file for module 'winston-azure-application-insights'. '/..../node_modules/winston-azure-application-insights/lib/winston-azure-application-insights.js' implicitly has an 'any' type.
  Try `npm install @types/winston-azure-application-insights` if it exists or add a new declaration (.d.ts) file containing `declare module 'winston-azure-application-insights';`

2 import { AzureApplicationInsightsLogger } from 'winston-azure-application-insights';
```

I have the following module definition in `src/missing-lib-types.d.ts`:
```
declare module 'winston-azure-application-insights';
```

Previous versions of ts-node-dev are fine and `tsc` runs without errors.

I've tried running with `ts-node-dev --no-deps --watch 'src' --no-notify ./src/app.ts` and `ts-node-dev ./src/app.ts`.  I'm running on macOS.

**Comment by whitecolor** [comment]
check if `ts-node` works, try `--files` option.

**Comment by plaa** [comment]
@whitecolor thanks. Adding `--files` to the `ts-node-dev` command line fixed the issue.  Prior to 1.0.0-pre.51 this flag wasn't needed.

Working command: `ts-node-dev --files --no-deps --watch 'src' --no-notify ./src/app.ts`
(Not sure what params are really needed, that's an existing command from the project)

Feel free to close this issue if you think this works as expected, or leave open if it's a regression.

**Comment by whitecolor** [comment]
This works as expected prior to this `files` option was `true` by default, but using this flag may slow down startup dramatically on a big project.
