### ISSUE TITLE
Allow optionally preserving logs as they originally are

### ISSUE THREAD

**Issue by dmattia** [whitecolor/ts-node-dev#210]
On line https://github.com/whitecolor/ts-node-dev/blob/master/src/log.ts#L31, this library updates all log messages that would normally be output from ts-node to have a `[LEVEL] timestamp` prefix (with the timestamp being optional).

This is problematic in cases where users want to keep their logs as JSON objects, because `[LEVEL] { some_json... }` is no longer valid json.

I would like a flag to preserve the logs as they originally are, without any prefix

**Comment by whitecolor** [comment]
This is for `ts-node-dev` output, not sure why it affects your output?
