### ISSUE TITLE
[Feature Request] Compilation progress indicator?

### ISSUE THREAD

**Issue by mewtlu** [whitecolor/ts-node-dev#211]
Hi there, I'm an avid user of ts-node-dev but running it on large codebases and a slow machine has shown lately that it's a little difficult to understand what the package is up to sometimes without the `--debug` flag enabled (which obviously I don't want all the time), so I feel some kind of progress indicator (even just a percentage or total of number of files compiled) and a status would be extremely beneficial!

Hope it's alright for me to post a feat req as an issue, feel free to close if not!

**Comment by whitecolor** [comment]
Files are required and compiled synchronously so it is not possible to estimate the current progress anyhow.

**Comment by mewtlu** [comment]
Ah okay that makes sense, even just status messages would be very helpful though, I find myself sitting and staring at a static console all too often, unsure whether it's just slow or has crashed. (Speaking of, rather than opening another issue I'll just ask here: any plans to upgrade to ts-node v9? As far as I can tell there's been significant performance upgrades)

**Comment by whitecolor** [comment]
I don't think that  "significant performance upgrades" in ts-node v9 is a real thing, it is more about the speed of TS compiler. Try to use it without type checking.

Will upgrade soon.

**Comment by mewtlu** [comment]
Ah okay that's fair, so we'll also reap the benefits once we've upgraded TS version? Through a quick test the latest ts-node currently feels faster than ts-node-dev which is unfortunate since ts-node-dev runs much better than ts-node+nodemon on my broken old machine. Thank you though!
