### ISSUE TITLE
Is it possible to get rif of restart logs

### ISSUE THREAD

**Issue by sahilrajput03** [whitecolor/ts-node-dev#214]
[INFO] 22:57:41 Restarting: this/this/file.js

 Can we disable this extra logging thing with any flag?

**Comment by sahilrajput03** [comment]
Like nodemon has quiet mode
nodemon -q or nodemon --quiet ??

**Comment by whitecolor** [comment]
Will add it soon.

**Comment by sahilrajput03** [comment]
Okay, thanks for feedback !! 
Thanks man, I'm gonna wait for it. :love_you_gesture:

**Comment by whitecolor** [comment]
Should work with `--quite` flag now.

**Comment by sahilrajput03** [comment]
yeah, it works now!!!
AMAAAZING!!!!! :LOVE: 😍😍😍😎😎😎😎😎😎😚😚😚😚
Thanks for all that effort and for this utility again, thanks a lot.
