### ISSUE TITLE
Use with mocha

### ISSUE THREAD

**Issue by ricardo-dlc** [whitecolor/ts-node-dev#218]
The script to use mocha with ts-node is:
`"test": "env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' mocha -r ts-node/register '*spec.ts'"`

Then how can I achieve that using ts-node-dev. I tried with: `"dev": "set debug=* && ts-node-dev --respawn --transpile-only mocha -r script.spec.ts"` and got no success. I'm unable to see reloading or even the mocha tests in the first run or change in the code.

I also tried with: `"dev": "set debug=* && mocha -r ts-node-dev --respawn --transpile-only script.spec.ts"` getting the following error:
```
> set debug=* && mocha -r ts-node-dev --respawn --transpile-only script.spec.ts

Error: No test files found: "test"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! script@0.0.0 dev: `set debug=* && mocha -r ts-node-dev --respawn --transpile-only script.spec.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the script@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-13T21_13_52_956Z-debug.log
```

**Comment by whitecolor** [comment]
As you can see ts-node-dev it self used mocha for a watched tests. I run it this way:

```
ts-node-dev -T --respawn --deps --watch lib node_modules/mocha/bin/mocha test/*.test.ts
```

**Comment by ricardo-dlc** [comment]
> As you can see ts-node-dev it self uses mocha for a watched tests. It can not be used via `--require` like ts-node, I run it this way:
> 
> ```
> ts-node-dev -T --respawn node_modules/mocha/bin/mocha test/*.test.ts
> ```

Thanks, this is what I'm looking for. Also sorry for not analyze the package.json so well in first step.
