### ISSUE TITLE
Inital Start up is very slow.

### ISSUE THREAD

**Issue by jsbroks** [whitecolor/ts-node-dev#221]
## Issue description

My initial compile-time takes about a 1.5 mins. When running with `ts-node` it's about 20 seconds, and `tsc` 10 seconds. Sadly I do not have the option of using `transpile-only` as this breaks `typeorm`.

```
[DEBUG] 10:14:54 services/api/src/index.ts added to watcher
[DEBUG] 10:15:01 services/api/src/index.ts compiled in 7118 ms
....
[DEBUG] 10:15:02 shared/orm/entities/DatasetRole.ts compiled in 920 ms
[DEBUG] 10:15:02 shared/orm/entities/FileDelete.ts added to watcher
[DEBUG] 10:15:02 shared/orm/entities/FileDelete.ts compiled in 796 ms
[DEBUG] 10:15:02 shared/orm/entities/DatasetRole.ts compiled in 13 ms
```

Im also using tsconfig-paths/register.

## Context

*OS version, ts-node-dev version*

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
When running with `ts-node` it's about 20 seconds.

*Did you try to run with `--files` option enabled?*
Improved performance to 1 min.

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
No, hopefully Ill have time next week to make one

**Comment by whitecolor** [comment]
```
services/api/src/index.ts compiled in 7118 ms
```
This is quite strange, is it a big file?

> transpile-only as this breaks typeorm

How is it breaking it?

**Comment by jsbroks** [comment]
@whitecolor thanks for the response! 

`index.ts` loads the apollo server and its only 175 lines but has about 20 lines of import statements. Files actually seem to help my performance, not really sure why or what's going on here.

Libraries like Typeorm require certain declarations for type inference at runtime so I cannot take advantage of transpileOnly.

Heres a little more context: Im running in a monorepo with these tsconfig files:


```json
// tsconfig.base.json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "declaration": true,
    "strict": true,
    "incremental": true,
    "strictPropertyInitialization": false,
    "sourceMap": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "baseUrl": ".",
    "types": ["reflect-metadata", "node", "jest"]
  },
  "exclude": [
    "**/node_modules",
    "**/dist",
    "**/build",
    "**/scripts",
    "**/*.test.ts",
    "**/*.spec.ts"
  ]
}
```

```json
// tsconfig.json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "jsx": "preserve",
    "skipLibCheck": true,
    "declaration": false,
    "experimentalDecorators": true,
    "sourceMap": false,
    "skipDefaultLibCheck": true,
    "paths": {
      "@shared/*": ["shared/*"]
    }
  }
}
```

```json
// services/api/tsconfig.json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist",
    "declaration": false,
    "sourceMap": false,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": ["src/**/*"]
}
```

**Comment by whitecolor** [comment]
you may try the latest, it uses ts-node 9

**Comment by jsbroks** [comment]
Cannot really debug enough to figure out what's going on... I'm going to close this for now.
