### ISSUE TITLE
ts-node-dev runs on invalid tsconfig.json

### ISSUE THREAD

**Issue by chicocode** [whitecolor/ts-node-dev#24]
If you have an invalid json configuration (but valid js object) `ts-node-dev` will run with no error:
i.e. (`tsconfig.json`):
```
{
  (...)
  "include": [
    "src/**/*.ts",
    "test/**/*.ts",
  ]
}
```
(the last comma in the `include` array makes the json config invalid)
This behavior is not all bad, but since `tsconfig.json` should  be always a valid json and I'd expect the same behavior as`ts-node` I think this is a that could be fixed.

**Comment by benjamingr** [comment]
This is coming from the tsconfig package https://github.com/TypeStrong/tsconfig/blob/master/src/tsconfig.ts#L187

**Comment by whitecolor** [comment]
So believe may close it?
