### ISSUE TITLE
ts-node-dev does not pass --files option to ts-node which drops local typings

### ISSUE THREAD

**Issue by dannycochran** [whitecolor/ts-node-dev#25]
ts-node requires passing `--files` or setting the env variable `TS_NODE_FILES` in order to respect typings from typeRoots, as of `ts-node@7.0.0`.

https://github.com/TypeStrong/ts-node/issues/625#issuecomment-401660263

The current workaround for this is to set that env variable because the `--files` flag is not respected.

**Comment by whitecolor** [comment]
I believe it should work already.
