### ISSUE TITLE
Error: Cannot find module 'tsconfig'

### ISSUE THREAD

**Issue by matt-erhart** [whitecolor/ts-node-dev#3]
```js
module.js:491
    throw err;
    ^

Error: Cannot find module 'tsconfig'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

tsconfig is in the usual spot in the root dir. Do I need to do anything special to point it to the right one?

**Comment by whitecolor** [comment]
you should add `ts-node` as dependency. I removed it to allow different versions of `ts-node` to be used.

**Comment by nolazybits** [comment]
I have the exact same problem.
Using `ts-node-dev 1.0.0-pre.16`

Thanks

**Comment by nolazybits** [comment]
found out I had to roll back to version `1.0.0-pre.5` to have it working again

**Comment by whitecolor** [comment]
latest version of `ts-node-dev` depends on `ts-node: *` package which depends on `tsconfig`

**Comment by kachkaev** [comment]
Also getting `Cannot find module 'tsconfig'` using `ts-node@5.0.0` and `ts-node-dev@1.0.0-pre.16`. Can this be reopened?

**Comment by whitecolor** [comment]
Seems ts-node stoped using this module for resolovgin config, I've a added as deps, please update `ts-node-dev`.

**Comment by bushmango** [comment]
I had to resolve this by manually installing tsconfig as well using the latest

**Comment by bushmango** [comment]
``` npm i tsconfig ```

**Comment by whitecolor** [comment]
@bushmango 
The latest version should install this dep https://github.com/whitecolor/ts-node-dev/blob/master/package.json#L49
