### ISSUE TITLE
Can support monitor yarn link module modifications?

### ISSUE THREAD

**Issue by wildtang** [whitecolor/ts-node-dev#34]
ts-node-dev is an Amazing project, Thanks.

I has a project grouped with two local TypeScript sub-projects.
(1) my-utils
(2) my-backend  (a Koa project)

Before development in a new PC, I will:
in my-utils folder execute yarn link
in my-backend folder execute yarn link my-utils

So when I modified source files of my-utils, I do not need to "publish my-utils to some repo server and then yarn add or yarn update in my-backend", the modifications of my-utils can be used by my-backend directly.

With ts-node-dev, How can respawn  my-backend service when I modified some source files of my-utils?
Thanks for your reply :)

**Comment by wildtang** [comment]
Yes, I found the solution:
in my-backend sub-project's tsconfig, inner "include" append two lines as below

  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "node_modules/my-utils/src/**/*.ts",
    "node_modules/my-utils/src/**/*.tsx",
]

**Comment by whitecolor** [comment]
So I believe may close it? Instead of `yarn link` use (yalc)[https://github.com/whitecolor/yalc] )
