### ISSUE TITLE
--preserve-symlinks isn't supported

### ISSUE THREAD

**Issue by intellix** [whitecolor/ts-node-dev#39]
Needing to use this to get symlinks/peerDeps working with a local dependency. 
This works: `node -r ts-node/register --preserve-symlinks src`
But even if I add the whitelist to ts-node-dev, this doesn't work: `ts-node-dev --preserve-symlinks src`

This works: `NODE_PRESERVE_SYMLINKS=1 ts-node-dev src`

**Comment by whitecolor** [comment]
There is `compilerOptions` parameter see https://github.com/TypeStrong/ts-node#cli-and-programmatic-options

**Comment by marcj** [comment]
It doesnt. 

In `ts-node` it works like that:

`node -r ts-node/register --preserve-symlinks src/main.ts`

but in ts-node-dev there's no such argument. Also setting

```
    "preserveSymlinks": true,
```

doesn't help for both.

**Comment by whitecolor** [comment]
Will reopen probably should handle those node's standard options.
