### ISSUE TITLE
Difference between "node-dev -r ts-node/register"?

### ISSUE THREAD

**Issue by windware** [whitecolor/ts-node-dev#4]
It seems I can accomplish the same feature by running node-dev with ts-node reigstered but does this package provide the same feature by a single command instead of providing ts-node as an argument? (Except for the new 3 launch parameters added.)

**Comment by whitecolor** [comment]
Please read the readme)

> It restarts target node process when any of required files changes (as standard node-dev) but shares Typescript compilation process between restarts. This significantly increases speed of restarting comparing to node-dev -r ts-node/register ..., nodemon -x ts-node ... variations because there is no need to instantiate ts-node compilation each time.

**Comment by windware** [comment]
Sorry, missed the most obvious place...
