### ISSUE TITLE
Cold start takes 2-3 minutes. Any way to improve?

### ISSUE THREAD

**Issue by hackhat** [whitecolor/ts-node-dev#41]

**Comment by whitecolor** [comment]
Is it a big project? Try to start with just `ts-node` the same result?

**Comment by hackhat** [comment]
Around 20k lines, express, redux, sockets.io. Ts-node is also a bit slow, but not that much.

**Comment by whitecolor** [comment]
How many js/ts files in your project? What OS?

**Comment by hackhat** [comment]
Win 10, 64 bit, around 20k lines, 1000 source code files + many deps.

**Comment by whitecolor** [comment]
`node_modules`are excluded by default,
So you have 1000 of TS files, each in average 20 lines, required by single running node process?

**Comment by whitecolor** [comment]
> Yes, kind of.

Interesting what kind of process/service is launched this way?

**Comment by hackhat** [comment]
Just a node server, nothing too fancy. Is just a backend server for a game.

**Comment by hackhat** [comment]
![image](https://user-images.githubusercontent.com/11173732/49718566-75b62c80-fc95-11e8-878e-1dd2b8701c64.png)

If I run this command it takes around 20 seconds. With ts-node-dev takes around 5 minutes now.

**Comment by MatxBerg** [comment]
We also have a projet, not as large as @hackhat but still, it takes about 5 seconds to load on MacOS but about 5 minutes to load on windows

**Comment by whitecolor** [comment]
@MatxBerg with `--transpileOnly`?

**Comment by whitecolor** [comment]
Will close for now
