### ISSUE TITLE
No support for node --eval flag

### ISSUE THREAD

**Issue by jeremyben** [whitecolor/ts-node-dev#43]
Hi, before getting into the issue, I would like to thank you for this package, as it is zero configuration. And I love zero config packages, especially in the JS ecosystem.

Now I have a problem with ts-node-dev to evaluate scripts from the CLI, with the `--eval` node flag.

```js
"scripts": {
  "start": "ts-node --eval \"console.log('Hello')\"",
  "dev-a": "ts-node-dev --eval \"console.log('Hello')\"",
  "dev-b": "ts-node-dev --eval -- \"console.log('Hello')\"",
}
```
- Script `start` with just ts-node works fine, prints `Hello`.

- Script `dev-a` prints `Usage: ts-node-dev [options] script [arguments]`, as it should be, given the readme section about node flags.

- Script `dev-b` prints an error `Error: Cannot find module 'console.log('Hello')'` since it probably evaluates the argument as a path to a module.

**Comment by whitecolor** [comment]
What is the use case for it?

**Comment by jeremyben** [comment]
I thought you might ask :)
I design my modules without side effect to avoid any surprise when sharing them.
A few examples :

```ts
// server.ts

export let app: Express.Application

export function bootstrapApp() {
  app = express()
  app.use(someMiddleware)
  app.use(someRouter)
  return app
}

export function startServer() {
  return bootstrapApp().listen(3000)
}
```

```ts
// operations.ts

export function backup() {
  // backup logic
}

export function restore() {
  // restore logic
}
```

I then evaluate with the node flag to avoid making entry points files for every module.
And the scripts would be

```js
"scripts": {
  "serve": "ts-node --eval \"require('./server').startServer()\""
  "backup": "ts-node --eval \"require('./operations').backup()\"",
  "restore": "ts-node --eval \"require('./operations').restore()\"",
}
```

It makes more sense in the case of the `operations.ts` file, since server modules are usually executed in an entry point file, but this entry point probably also deals with database connections, and there are cases where you need to decouple that.

**Comment by whitecolor** [comment]
Well, this is due to `node-dev` doesn't support such "script-less" scenario. Not sure if it is really worth to support it for dev/watch workflow. Can be done with additional one-line script files.

**Comment by jeremyben** [comment]
Ok this is on `node-dev`, didn't know.
I guess you're right about this not being worth it in a dev/watch workflow.
Thanks for your time !
