### ISSUE TITLE
process.exit() actually doesn't work

### ISSUE THREAD

**Issue by devlato** [whitecolor/ts-node-dev#45]
Hello,

I've noticed that there are cases when `process.exit()` stops working and everything just hangs.

**Comment by whitecolor** [comment]
Is it waiting for files to change? Did you use `--respawn` arg?

**Comment by devlato** [comment]
@whitecolor No, I run it without any flags at all.

**Comment by whitecolor** [comment]
Then provide the code and I will reopen it.

**Comment by mehmetnyarar** [comment]
I'd like the current process to be stopped if any fatal error occurs in my code, for example not being able to connect to the database.

Based on the suggestion above, I provided `--respawn` and `--exit-child` flags but it seems they don't have any effect.

```json
{
  "scripts": {
    "dev": "ts-node-dev --exit-child --respawn --transpileOnly --ignore-watch node_modules -r tsconfig-paths/register src",
  }
}
```

**Comment by whitecolor** [comment]
@mehmetnyarar 
`--exit-child` just adds `SIGTERM` handler which does `process.exit()`
`--respawn` makes `ts-node-dev` NOT to stop working when child does exit, and restart it on change.

You may provide your code sample.

**Comment by verekia** [comment]
I couldn't get ts-node-dev or nodemon to restart on crash, but simply re-running my script like that did the trick!

```json
"scripts": {
  "dev": "ts-node-dev --transpile-only index.ts; yarn dev",
}
```
