### ISSUE TITLE
how to close desktop notice, but keep terminal notice

### ISSUE THREAD

**Issue by s97712** [whitecolor/ts-node-dev#46]
` # ts-node-dev --nofify false index.ts` will close all notify, can I close desktop notice, but keep terminal notice?

**Comment by whitecolor** [comment]
Actually (as stated in https://github.com/fgnass/node-dev docs) --no-notify removes only desktop notifications.

**Comment by SanthoshRaju91** [comment]
Just for reference to developers who is looking for answers.  `ts-node-dev --notify false` works.
