### ISSUE TITLE
Allow post params in command line

### ISSUE THREAD

**Issue by DavidBabel** [whitecolor/ts-node-dev#53]
Yet this is possible : 

```json
"scripts": {
  "start": "ts-node-dev src/main/index.ts",
  "watch": "ts-node-dev --respawn src/main/index.ts",
}
```

This is not : 
```json
"scripts": {
  "start": "ts-node-dev src/main/index.ts",
  "watch": "yarn start -- --respawn",
// or with modern npm
  "watch": "yarn start --respawn"
}
```

Should be great to allow : 
`ts-node-dev src/main/index.ts --respawn`
To fix this issue

**Comment by whitecolor** [comment]
`ts-node-dev src/main/index.ts --respawn`

This is not possible, because script arguments (for index.ts itself) are possible.
