### ISSUE TITLE
Feature Request Lazy Time

### ISSUE THREAD

**Issue by Gr33nbl00d** [whitecolor/ts-node-dev#54]
It would be nice to have a lazy reaction time of restarting configurable.

The idea is that the there need to be no change in that time in order to restart.
When changing multiple files projects it keeps always restarting eating up cpu power.

So i could conifgure for example 30sec means: No change since 30 sec than restart

**Comment by whitecolor** [comment]
See the readme, there were added two options for polling mode `interval` and `debounce`, the latest probably that might work for you.
