### ISSUE TITLE
Legacy watch mode

### ISSUE THREAD

**Issue by pvtri96** [whitecolor/ts-node-dev#55]
Hi @whitecolor,

I really love your project, it's awesome.

But I am running into a problem setting up ts-node-dev within a Docker container, which is using a mounted driver. In Nodemon documentation, they are having [Legacy Watch](https://github.com/remy/nodemon#application-isnt-restarting) mode that works very well in this case.

It would be nice if we also have something like this.
🚀

**Comment by 19majkel94** [comment]
@pvtri96 
There's a pending pull request for that in `node-dev` repo:
https://github.com/fgnass/node-dev/pull/217

Look like it's abandoned, maybe it's time to split and fork it to not rely on a dead code? @whitecolor

**Comment by JacopoPatroclo** [comment]
Hi, I've checked the pending pull that @19majkel94 suggested and the solution appears to be the use of `--poll` as a ts-node parameter, so like this `ts-node-dev --poll --respawn --transpileOnly src/app.ts`.

**Comment by jeremyben** [comment]
@19majkel94 You can make the same pull request here (in `lib/index.js`), because ts-node-dev is already a fork of node-dev, not a wrapper, as you can see in the code.

**Comment by 19majkel94** [comment]
@jeremyben 
I've opened the PR #58 here in `ts-node-dev` but it's still waiting for review and merge by @whitecolor 😕

**Comment by whitecolor** [comment]
I always used `ts-node-dev --poll` with docker on windows without any problem.

**Comment by 19majkel94** [comment]
@whitecolor 
If you like 30% CPU usage from polling every 100ms - yeah, it works without any problem.
I prefer 3s and 3% CPU usage, especially while working on slower hardware (old notebook).

**Comment by whitecolor** [comment]
Ok, will merge and publish it.

**Comment by 19majkel94** [comment]
Looks like it's working and not consuming tons of CPU time 🎉 Thanks! 💪

**Comment by whitecolor** [comment]
> Looks like it's working and not consuming tons of CPU time 🎉 Thanks! 💪

What params do you use?

**Comment by whitecolor** [comment]
@19majkel94 
What params do you use to run?

**Comment by pvtri96** [comment]
I am using these params for my development process:
```
ts-node-dev --no-deps --respawn --poll --interval 1000 src/main.ts
```

The CPU cost is using around 1-3% (this number will scale depending on how many the files I have) which is a huge improvement 🚀.
