### ISSUE TITLE
Can ts-node-dev be used with esm?

### ISSUE THREAD

**Issue by karensg** [whitecolor/ts-node-dev#65]
I can run it with ts-node itself with
`node -r esm -r ts-node/register...`

But I assume that at this moment ts-node-dev can not be combined with esm?

**Comment by steida** [comment]
I am using it in https://github.com/este/este and it works. But note there is a bug, so version must be fixed. Check esm issues.

**Comment by whitecolor** [comment]
I'm not sure, but probably should.

**Comment by karensg** [comment]
How would you transfrom this to `ts-node-dev`?
`node -r esm -r ts-node/register/transpile-only src/index.ts`

I don't see the register options for `ts-node-dev` library.

**Comment by whitecolor** [comment]
`-r` should work, try:
`ts-node-dev -r esm --transpile-only src/index.ts`

**Comment by whitecolor** [comment]
@karensg 
Check it with the latest version, I inserted the check.

**Comment by karensg** [comment]
Thanks for your help!

Tried with v37, the flag does not seem to influence anything. Using what you suggested:
`ts-node-dev -r esm --transpile-only src/index.ts`

Getting these kind of errors:
```
import { readFileSync } from 'fs';
       ^
SyntaxError: Unexpected token {
```

**Comment by whitecolor** [comment]
@karensg
Should be working now.

**Comment by steida** [comment]
Interesting. New version does not work with the old versions of "esm": "3.2.20" but works with the last version of esm. Thank you.

**Comment by karensg** [comment]
It works for me too. Absolute madness!
Thanks!

**Comment by whitecolor** [comment]
> Interesting. New version does not work with the old versions of "esm": "3.2.20" but works with the last version of esm. Thank you. It's fixed for me.

Well it could be handled, but don't think it is very relevant.

**Comment by alesso-x** [comment]
How do I run `ts-node-dev` with `ts-node/esm`? related issue https://github.com/TypeStrong/ts-node/issues/1007. 

I have a sample repo where I'm trying to use [top level await](https://github.com/alesso-x/top-level-await/blob/106ffcf091b3a1b56fc37a615266e611a22f4e66/package.json#L8-L9) with scripts for `ts-node` and `ts-node-dev`. The `ts-node` version is run by `node --loader ts-node/esm`.

**Comment by whitecolor** [comment]
@alesso-x 
I'm not sure how ESM loader works and how it should be configured bu [this test](https://github.com/whitecolor/ts-node-dev/blob/master/test/tsnd.test.ts#L149) is passing.

**Comment by sippeangelo** [comment]
I've completely given up on the mess that is ESM and opted for [fix-esm](https://www.npmjs.com/package/fix-esm). Worked fine with ts-node-dev for me.

**Comment by homerjam** [comment]
> How do I run `ts-node-dev` with `ts-node/esm`? related issue [TypeStrong/ts-node#1007](https://github.com/TypeStrong/ts-node/issues/1007).
> 
> I have a sample repo where I'm trying to use [top level await](https://github.com/alesso-x/top-level-await/blob/106ffcf091b3a1b56fc37a615266e611a22f4e66/package.json#L8-L9) with scripts for `ts-node` and `ts-node-dev`. The `ts-node` version is run by `node --loader ts-node/esm`. I also tried `ts-node-dev -r esm` but that did not work.

https://github.com/wclr/ts-node-dev/issues/212#issuecomment-974699400
