### ISSUE TITLE
priorNodeArgs is undefined at `lib/index.js:91

### ISSUE THREAD

**Issue by kavika-1** [whitecolor/ts-node-dev#67]
Running ts-node-dev inside node programmatically, on latest (1.0.0-pre.38).  It emits the following:
````
Using ts-node version 8.1.0, typescript version 3.2.4
Warning: Cannot read property 'concat' of undefined Use --force to continue.
````
Looks like `priorNodeArgs` is `undefined` at `lib/index.js:91`
````
    cmd = opts.priorNodeArgs.concat(['-r', childHookPath]).concat(cmd)
````
Also, seems the current repo doesn't show this change or version, master seems to be at pre.34?

**Comment by whitecolor** [comment]
This is strange, did you update from the previous version? Seems like bin/ts-node-dev was not updated.

Upgrage please from to new one.

**Comment by kavika-1** [comment]
Cool - thanks - that fixed it.  It is now at pre.39.
