### ISSUE TITLE
compile error is not printed out

### ISSUE THREAD

**Issue by capaj** [whitecolor/ts-node-dev#68]
Sometimes when I run with a syntax error, I get this output:
```
> looop@ be /home/capaj/work-repos/looop/project-alpha
> cd ./back-end && NODE_ENV=development LOOOP_ENVIRONMENT=dev DEBUG=looop*,knex:query,knex:bindings ts-node-dev --transpileOnly src/server.js

Using ts-node version 8.1.0, typescript version 3.4.5
  looop:knexfile dbName:  looop +0ms
  looop:aws mocking aws.SES +0ms
  looop:aws mocking aws.SQS +0ms
[ERROR] 20:05:54 ⨯ Unable to compile TypeScript:

```

would be nicer if it showed an error

**Comment by promethe42** [comment]
I have the exact same issue. `ts-node-dev` becomes pretty much useless since I don't know why the build fails.

**Comment by whitecolor** [comment]
I've seen this behavior too, but usually, I don't look at the console while dev 
All the errors are shown in IDE, and to go console only when something doesn't work. And often use `transpileOnly` option to speed things up. So I had no chance to suffer from this bug. -)

@promethe42 
Does it work usually, and breaks only on specific cases?

**Comment by promethe42** [comment]
My whole build/run env is in Docker (Compose) using the `node:10-alpine` image.
Just now I had typing errors showing as expected in the console after removing the `transpileOnly` flag.

**Comment by whitecolor** [comment]
So I believe there should be no TS error if transpile only is used.

**Comment by promethe42** [comment]
> So I believe there should be no TS error if transpile only is used.

But as stated by OP, the console says:

```
[ERROR] 20:05:54 ⨯ Unable to compile TypeScript:
```

even when `transpileOnly` is used.

**Comment by whitecolor** [comment]
what does `ts-node` outputs for this case?

**Comment by seiyria** [comment]
For me, it prints the actual error: 
![image](https://user-images.githubusercontent.com/763609/71264382-9afa6380-2309-11ea-8e10-f98aa1736e19.png)

**Comment by whitecolor** [comment]
This issue probably relates to running with docker (docker-compose). 

Use ts-node's `--pretty` flag it fixes the error output with docker-compose.

**Comment by seiyria** [comment]
I'll try that, but I'm not using docker so I'd wager that isn't the problem here. Unless ts-node-dev is using it under the hood, but I don't think that's the case either(?)

**Comment by whitecolor** [comment]
@seiyria in your case you should not use `--transpile-only` to see TS error.

**Comment by seiyria** [comment]
That's gonna be pretty rough for reload speed though (right?), and that's kinda why I'm using the tool. Are there any other flags I should pass or not pass?

**Comment by whitecolor** [comment]
> That's gonna be pretty rough for reload speed though

No for large codebase it will only affect the first startup time. This is what ts-node-dev was made for.

**Comment by IonelLupu** [comment]
what the... I don't get errors in the console too. What happened? `ts-node` and `tsc` show errors correctly

**Comment by heivo** [comment]
Did anyone figure out how to solve this?

**Comment by DarkLite1** [comment]
> what the... I don't get errors in the console too. What happened? `ts-node` and `tsc` show errors correctly

I'm having the same issue, no TS errors displayed in the console when running:
```js
ts-node-dev --respawn -r dotenv/config src/index.ts
ts-node-dev --respawn --transpile-only -r dotenv/config src/index.ts
```

**Comment by IonelLupu** [comment]
@whitecolor I see you closed this. Is it fixed?

**Comment by whitecolor** [comment]
@IonelLupu 
I believe it should be, if it was due https://github.com/whitecolor/ts-node-dev/issues/119.
