### ISSUE TITLE
Add option to disable notification

### ISSUE THREAD

**Issue by Richienb** [whitecolor/ts-node-dev#72]
It would be useful if I could disable the notification feature...

**Comment by whitecolor** [comment]
Actually (as stated in https://github.com/fgnass/node-dev docs) --no-notify removes only desktop notifications.

**Comment by Richienb** [comment]
Thanks!

**Comment by raine** [comment]
`ts-node-dev --help` should show the options, `--no-notify` included

**Comment by gunar** [comment]
`ts-node-dev --no-notify src/index.ts` does not disable notifications for me on `1.0.0-pre.4`
