### ISSUE TITLE
not restart when ts file loaded via fs.readFileSync

### ISSUE THREAD

**Issue by TrungRueta** [whitecolor/ts-node-dev#73]
I have case when 1 ts file load other files (ts) inside 1 folder. I use glob syntax to load them. problem is: when change files inside folder, ts-node-dev not detect changes and not restart.

A other issue is i read in document that tsnd build on top of node-dev but tsnd not reference to node-dev config json file like node-dev.

solution:
i suggest we can have manual command to reload tsnd anytime we want, like nodemon has `rs` command to force reload. I love tsnd because it reload veryfast since it share compiled file in cache, not like nodemon + ts-node always slower when full reload. but seem tsnd still have some bugs.

**Comment by whitecolor** [comment]
ts-node-dev only watches for **required** files, not loaded, that maybe many solutions you can invent to make ts-node-dev restart when you need.

I'm not sure what `rs` nodemn's command and how it works.

**Comment by TrungRueta** [comment]
hi @whitecolor 
about nodemon manual restart you can read it from here:
[manual-restart :: nodemon](https://github.com/remy/nodemon#manual-restarting)

yes, probably i just can ctrl + c and run command again, but like this i will lost fast compile feature from ts-node-dev. What i love tsnd is how it fast compile files changed and keep remember other ones. if full restart then we back same stage with nodemon + ts-node, it really slow than tsnd a lot. 

any change to keep tsnd sharing compile file but we change restart system from node-dev to nodemon ?

**Comment by whitecolor** [comment]
> about nodemon manual restart you can read it from here:
> [manual-restart :: nodemon](https://github.com/remy/nodemon#manual-restarting)

I don't get how this is implemented.

As for possible solutions, you could set your own watcher script for the folder (using one like wth `chokidar` or something) that would modify some required file. THis would make the restart process fully automatic.

This is a bit hacky. But actually, all the dev processes is a big hack.
