### ISSUE TITLE
Debug with webstorm or vscode

### ISSUE THREAD

**Issue by QuantumInformation** [whitecolor/ts-node-dev#75]
Are there any guides on how to Debug your ts files with webstorm or vscode using ts-node-dev?

I tried:

<img width="1063" alt="Screenshot 2019-06-08 at 21 53 19" src="https://user-images.githubusercontent.com/216566/59151243-5deb1580-8a38-11e9-80bf-a813c40649f3.png">

**Comment by whitecolor** [comment]
please, read some issues about vscode debugger

**Comment by jazib-m** [comment]
Man I'm having the same issue with VS code

**Comment by Pitros** [comment]
@jazib-m launch `ts-node-dev` with `--inspect` and then just attach to running instance:
```
 {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229,
            "restart": true
 }
```

**Comment by ludetc** [comment]
for anyone struggling to get webstorm to attach to either process. Here's the trick

node parameters => --inspect=9229
javascript file => node_modules\ts-node-dev\bin\ts-node-dev
Application Parameters => --project tsconfigNode.json --inspect=9001 --  app.ts

**Comment by QuantumInformation** [comment]
all good?

**Comment by Tinadim** [comment]
@ludetc while your instructions worked for me when I first ran it, as soon as I do a change, the process restarts but the debugger doesn't reconnect. Any advices there?

<img width="713" alt="Screen Shot 2020-03-30 at 11 21 14" src="https://user-images.githubusercontent.com/7933739/77923306-a5b58480-7278-11ea-89f2-9354798c0f65.png">

**Comment by mikeporterdev** [comment]
@Tinadim I'm having the same issue, did you ever find a resolution for this?
