### ISSUE TITLE
Re-run script on file changes even after finished execution

### ISSUE THREAD

**Issue by bdadam** [whitecolor/ts-node-dev#77]
Consider the following script:
```ts
// index.ts
console.log("Finished");
```

## What happens
When running `tsnd index.ts` it runs the script and exists as the script finishes.

## What should happen
When running `tsnd index.ts` it runs the script and waits for changes. If the file is changed it re-runs it again. Just as e.g. `nodemon` does it.

**Comment by whitecolor** [comment]
there is a `--respawn` param

**Comment by bdadam** [comment]
Oh, wow. I somehow never noticed it... Thanks @whitecolor.
