### ISSUE TITLE
Doesn't kill child process

### ISSUE THREAD

**Issue by timsuchanek** [whitecolor/ts-node-dev#79]
A simple script like this:
```ts
import { spawn } from 'child_process'

const child = spawn('./bin.js')
child.stdout.on('data', data => {
  console.log(data.toString())
})
```
will not be killed properly and on every reload another child will be spawned.

Reproduction: https://github.com/timsuchanek/ts-node-dev-child

A couple of thoughts:
1. I just tried it out, it was already broken in `node-dev`.
2. I highly recommend removing the non-standard behavior of not exiting, as soon as you add a process.on('SIGTERM') -> It took us about 2 weeks to find that weird behavior out. https://github.com/fgnass/node-dev#graceful-restarts
3. I don't know if this is a limitation by design based on the require stuff, but it doesn't happen with `nodemon`.

`tsc-watch` uses this approach: [listing the child processes and killing them](https://github.com/gilamran/tsc-watch/blob/master/lib/killer.js).

We're heavily relying on this with Prisma and really like `ts-node-dev` so far, so if you need a PR for this or any help, let us know.

**Comment by whitecolor** [comment]
you mean child process is not killed? btw try `--tree-kill` option.

**Comment by timsuchanek** [comment]
Thanks, that's exactly what I meant! I'll try the `--tree-kill` out. In my testing the SIGTERM process.exit didn't kill the child process of the running process properly.

Optimally we don't have to add any `process.on('SIGTERM')` to keep our examples clean, as when people see that, they'll copy that stuff over into their production code.

**Comment by timsuchanek** [comment]
`--tree-kill` works perfectly 👍 
So if you add it to the README, we can close this.
I would still consider rethinking this:
https://github.com/whitecolor/ts-node-dev/blob/24813393769d23da9e585c157b3375f594ecba5e/lib/wrap.js#L26
As there is already the IPC option.

**Comment by abhisekp** [comment]
@whitecolor I'm using the following options but it doesn't kill the process running the `--inspect`

```sh
cross-env-shell DEBUG=app* ts-node-dev  --tree-kill --no-deps --clear --transpileOnly --debounce=5000 --watch=config --nolazy --inspect=9259 -- index.js
```

**Comment by whitecolor** [comment]
Need repro example if the problem persists.

**Comment by joemags-apps** [comment]
![image](https://user-images.githubusercontent.com/63977646/106763310-5af65d00-663f-11eb-9d59-6a3717d93ea3.png)


Solved with `--exit-child`
