### ISSUE TITLE
The package is not starting in version 1.0.0-pre.40 in Windows

### ISSUE THREAD

**Issue by httpiago** [whitecolor/ts-node-dev#80]
I'm trying to use the package in a new project but it was taking so long time to start (more than 5 minutes), I went to investigate and tried to install an older version, more specifically version 1.0.0-pre.39 and it worked perfectly, so you introduced a bug in the last update. 😕

### Steps to reproduce the problem

Just follow the mini tutorial described in the README and try to start the app:
```
ts-node-dev index.ts
```

### Information on the environment

- **OS**: Windows 10
- **Node**: 12.2.0
- **Yarn**: 1.16.0
- **ts-node-dev**: 1.0.0-pre.40
- **Typescript**: 3.5.2

**Comment by whitecolor** [comment]
I always test and run on the latest version, Not sure what it can be, something with `ignore` option?

**Comment by httpiago** [comment]
### Solution

The problem goes away when the file "tsconfig.json" is created.
At the time I created this issue, I thought that [ts-node](https://github.com/TypeStrong/ts-node) generate this file in memory when it was started.

Here is my tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "lib": ["es2016"],
    "allowJs": true,
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "noEmitOnError": true,
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```
