### ISSUE TITLE
Add manual restart option

### ISSUE THREAD

**Issue by sarangjo** [whitecolor/ts-node-dev#82]
`nodemon` has an option to enter `rs<CR>` in the command line which manually restarts the process without having to kill it and re-run `ts-node-dev`. This would be a useful feature to have!

I'm currently looking into how `nodemon` implements the manual restart, will report back how feasible integrating that would be for `ts-node-dev`.

**Comment by sarangjo** [comment]
Alright, I think I have a quick fix up and running that works in basic cases. I want to do some more stress testing before opening up a PR, but in the meantime I am open to feedback and questions.

https://github.com/sarangjo/ts-node-dev/tree/manual-restart

**Comment by whitecolor** [comment]
just make a PR, try to do minima necessary changes to the code.

**Comment by staeke** [comment]
go make the PR @sarangjo !
