### ISSUE TITLE
Question / Feature Request: support yarn workspace

### ISSUE THREAD

**Issue by jtushman** [whitecolor/ts-node-dev#84]
ts-node-dev rocks -- thanks for the project!

I am using yarn workspaces.  consider the following:

```
/project
   package.json  (a yarn workspace)
   /data
      package.json
   /server
      package.json  (server depends on data)
```

if I run (in /server):
`ts-node-dev --respawn --transpileOnly --ignore-watch node_modules src/index.ts`

when I make changes in `data` -- it does not restart.  Is there away to make that happen?

Thanks!

**Comment by whitecolor** [comment]
ts-node-dev watches only files required by your script

**Comment by jtushman** [comment]
cool thanks -- closing

**Comment by dmks** [comment]
@jtushman  how did you solve your problem? Thanks
