### ISSUE TITLE
Unable to pass --log-error to ts-node

### ISSUE THREAD

**Issue by dshook** [whitecolor/ts-node-dev#88]
I've tried lots and lots of combinations of the flag placement and optionally adding "true" or "1" after it but I always get this error:

`/usr/local/bin/node: bad option: --log-error`

My command I've been trying to launch with is: 
`ts-node-dev --log-error true --project ./app/tsconfig.json ./app/server.ts`

**Comment by whitecolor** [comment]
Should work with latest.
