### ISSUE TITLE
paths option(tsconfig.json) is ignored

### ISSUE THREAD

**Issue by jjangga0214** [whitecolor/ts-node-dev#95]
# Settings

##### tsconfig.json

Other options are omiited for brevity.

```js
{
  "compilerOptions": {
    "baseUrl": "./src"
    "paths": {
      "#/*": ["./*"]
    }
  }
}
```

##### command

```bash
ts-node-dev --respawn --transpileOnly src/index.ts
```

##### src/index.ts

```ts
import { foo } from '#/foo'

console.log(`index.ts uses ${foo}`)
```

# Problem

When I edit foo.ts, which index.ts depends on, ts-node-dev does not respawn. I guess it's because ts-node-dev does not consider the **paths** option in tsconfig.json.

**Comment by jjangga0214** [comment]
# Workaround

Here is a workaround for folks with the same problem.
```bash
# remove ts-node-dev
npm uninstall ts-node-dev
npm install concurrently node-dev --save-dev
```
Install [concurrently](https://github.com/kimmobrunfeldt/concurrently) (or another preferred alternative) and node-dev(or maybe another like nodemon).

```bash
concurrently 'tsc -w' 'node-dev --respawn dist/index.js'
```

**Comment by whitecolor** [comment]
This is strange "workaround" =) 

Should this even work with node.js without special plugins?

TS compiler doesn't even transform require paths like '#/foo', so it should just give the error `Cannot find module '#/foo'`

There is a module https://github.com/dividab/tsconfig-paths allows to handle tsconfig's paths option with node.js

**Comment by jjangga0214** [comment]
@whitecolor 

Thank you for the recommendation :) 
While tsconfig-paths works on runtime, I've been using [link-module-alias](https://github.com/Rush/link-module-alias), which sets aliases before runtime by making symlink in node_modules. (And by this aspect, it has some other benefits especially on plain node project, by the way)

> TS compiler doesn't transform require paths like '#/foo',

Yes, the compiler literally compiles it "as-is".

> so it should just give the error Cannot find module '#/foo'

Well.. no. Actually the compiler does just works without an error, warning or complaining. If you want to get more detail, you can refer [ts handbook#path-mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping), or a community article about using module aliases with ts <https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353>.

Anyway, I want to say I seriously suggest ts-node-dev's respecting tsconfig paths. Otherwise, people using module aliases just can't use ts-node-dev even if they want.  

P.S. 

> This is strange "workaround" =)

"strange"..? Hmm, why?
Well, I personally think it's also quite good approach. There would be pros and cons.

**pros**

* Able to choose the tool we prefer. node-dev, nodemon, forever, pm2(maaaybe), or whatever.
* `tsc -w` is stable, so straight-forward and beginner-friendly. 
* More close to production-like condition. Node process would "directly" consume file system. (Of course this doesn't neccessarily mean ts-node-dev has a disadvantage.)

**cons** 

* We should composite different tools by ourselves.
* Maybe it looks not so "neat" ?

And it works smoothly. [jjangga0214/koa-helloworld](https://github.com/jjangga0214/ts-boilerplate) is a working example. You can clone it, run `yarn dev`, and then edit some ts files. Then it would automatically restart the node process seamlessly.

**Comment by whitecolor** [comment]
`tsc --watch` creates *.js files `ts-node` (not `ts-node-dev`, but `ts-node`) was created to avoid. 

If you ok with this *.js filles all around while dev, it is just another approach.

Also I prefer to use `yarn workspaces` instead of tsconfig `paths` and other "workarounds" like mentioned link-module-alias.

**Comment by jjangga0214** [comment]
@whitecolor The main point of this issue is asking if ts-node-dev would repect `paths`. I think it's cool and necessary. How do you think?

**Comment by whitecolor** [comment]
This is a task for another package, as I said you may use https://github.com/dividab/tsconfig-paths to achieve that if needed, setup is quite transparent.

**Comment by jjangga0214** [comment]
Closing this issue. Thanks for the response anyway :)

**Comment by microcipcip** [comment]
If anyone has issues with this, try the `module-alias` plugin. So far it's the cleanest solution I've found. In short, you have to set `tsconfig.json` like this:
```
{
  "compilerOptions": {
     "outDir": "./build/",
     "baseUrl": ".",
     "paths": {
       /* IMPORTANT: this must be the same of 'src/utils/aliases' */
       "@src/*": ["src/*"]
     },    
}
```

Then create a `src/aliases.ts` file like this:
```
import moduleAlias from 'module-alias';
import path from 'path';

const IS_DEV = process.env.NODE_ENV === 'development';
const rootPath = path.resolve(__dirname, '..', '..');
const rootPathDev = path.resolve(rootPath, 'src');
const rootPathProd = path.resolve(rootPath, 'build');
moduleAlias.addAliases({
  '@src': IS_DEV ? rootPathDev : rootPathProd,
});
```

Then, in the `src/index.ts` file, or in whatever is your entry file, add as first import this:
```
import './aliases';
import http from 'http';
import { app } from '@src/app';
....etc
```

**Comment by s-h-a-d-o-w** [comment]
@whitecolor I would recommend to add a note about this (also mentioning `baseUrl`, since one really doesn't have to use `paths` for things to break) in `points of notice` in the `README`.

Because while I love `ts-node-dev` for the reason you mentioned in this issue, I almost just threw in the towel until I stumbled across your recommendation to use `tsconfig-paths`. Which is so simple to set up but... why would one even think about looking for it in the first place? At least all I perceived was an inconsistency between `tsc` and `ts-node-dev` and assumed something was broken.

**Comment by coler-j** [comment]
@whitecolor tsconfig paths does not seem to work with `ts-node-dev`. It worked well previously with nodemon and ts-node.

**Comment by whitecolor** [comment]
Not sure why it may not work, when I used it worked ok.

**Comment by coler-j** [comment]
Please disregard. I was a bit confused when running a `nextjs` customer server, that first passed through ts-node for the server and than passed through webpack for the react code. Think I have it figured out now.

**Comment by soupman99** [comment]
For anyone finding this and want a two-liner here it is:
`npm i -D tsconfig-paths`

then in your package.json add a script like this:
` "dev": "tsnd --respawn -r tsconfig-paths/register *pathtoyourmainfile* " `

**Comment by cyraid** [comment]
> For anyone finding this and want a two-liner here it is:
> `npm i -D tsconfig-paths`
> 
> then in your package.json add a script like this:
> `"dev": "tsnd --respawn -r tsconfig-paths/register *pathtoyourmainfile* "`

It doesn't work for me, but I have a -P path/to/tsconfig.json  as well.. It might be throwing things off?

**Comment by dennislo** [comment]
Thanks @microcipcip for directing me to [module-alias](https://github.com/ilearnio/module-alias) plugin, since the other comments e.g `tsconfig-paths` did not `work.`

I created a `src/aliases.ts` file like this:
```
import moduleAlias from 'module-alias'

moduleAlias.addAliases({
  '#v1': __dirname + '/',
  '#v2': __dirname + '/v2'
})
```

Then, in the `src/index.ts` file, I added this as first import:
 
 ```
import './aliases'; // MUST BE FIRST!!
 
// Now you can use the `#v1` for absolute imports
import { app } from '#v1/app';
```

Inside my `tsconfig.json` I added this so my IDE can recognise the path:
```
    "baseUrl": "." /* Base directory to resolve non-absolute module names. */,
    "paths": {
      "#v1/*": ["./src/*"],
    } /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */,
```

I have a `dev` script inside my `package.json` file

```
"dev": "ts-node-dev --respawn --transpile-only ./src",
```

> If anyone has issues with this, try the [module-alias](https://github.com/ilearnio/module-alias) plugin. So far it's the cleanest solution I've found and it is working all right!
> 
> Given a directory structure like the following:
> 
> ```
> - build/                 // Here is the typescript outDir folder
> - src/                   // Here is where we have all the app files
> - src/index.ts
> - src/app.ts
> - package.json
> ```
> 
> Create a `src/aliases.ts` file like this:
> 
> ```
> import moduleAlias from 'module-alias';
> import path from 'path';
> 
> const IS_DEV = process.env.NODE_ENV === 'development';
> const rootPath = path.resolve(__dirname, '..', '..');
> const rootPathDev = path.resolve(rootPath, 'src');
> const rootPathProd = path.resolve(rootPath, 'build');
> moduleAlias.addAliases({
>   '@src': IS_DEV ? rootPathDev : rootPathProd,
> });
> ```
> 
> Then, in the `src/index.ts` file, or in whatever is your entry file, add this as first import:
> 
> ```
> import './aliases'; // MUST BE FIRST!!
> 
> // Now you can use the `@src` for absolute imports
> import { app } from '@src/app';
> ```
> 
> Finally, set `tsconfig.json` like this (mostly to make typescript and your IDE recognise the path):
> 
> ```
> {
>   "compilerOptions": {
>      "outDir": "./build/",
>      "baseUrl": ".",
>      "paths": {
>        /* IMPORTANT: this must be the same of 'src/aliases.ts' */
>        "@src/*": ["src/*"]
>      },    
> }
> ```

**Comment by IvanovRoman** [comment]
And ignored `baseUrl` in tsconfig.json

**Comment by fatihaziz** [comment]
maybe my workaround will help:
1. install required plugins:
`npm i -D ttypescript typescript-transform-paths ts-node tsconfig-paths`. 
these are packages that will help us to transform the paths.
2. then, on tsconfig.json, i put:

       {
        "ts-node": {
          "transpileOnly": true,
          "require": [  // set this so you dont need to use ts-node -r 
        	"typescript-transform-paths/register",
        	"tsconfig-paths/register"
           ]
        },         
	    "compilerOptions": {
		   "composite": true,
		   "rootDir": ".", // must define
		   "baseUrl": "src", // must define, the paths will relative to this
		   "outDir": "lib", 
		   "skipLibCheck": false,
		   "paths": {
			"@app/*": ["./*"],
			"@controllers/*": ["./controllers/*"],
           },
		    "plugins": [
			  { "transform": "typescript-transform-paths" }
		    ]
        }
       }

3. then we can use this on our codes everywhere:
          
       import myControllers from "@controllers/main.ts"

4. then to compile, we need to run `npx ttsc -p tsconfig.json` , we use npx so we dont need to install ttypescript globally
5. and to run on ts-node, we can simply run `npx ts-node -p tsconfig.json src/app.ts`, also npx for ts-node.

My conclusion: 
To workaround with ts-node paths, we need tsconfig-paths required on ts-node runtime.
but on production we just need to compile them into absolute path, so we use ttypescript and typescript-transform-paths to compile then transform the relative path to absolute path.
then the program can work fine with `node` without registering tsconfig-paths or any plugins
like `node lib/index.js`

I hope this solution will help,
also sorry if my word kinda messed up, i try to explain it as simple as possible.

**Comment by ndpniraj** [comment]
Thanks @soupman99 it works like charm
